name: climate-engine
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - pyarrow
  - scikit-learn
  - joblib
  - tqdm
  - jupyter
  - ipykernel
  - pip

  - pip:
    - torch --index-url https://download.pytorch.org/whl/cu126
    - torchvision --index-url https://download.pytorch.org/whl/cu126
    - torchaudio --index-url https://download.pytorch.org/whl/cu126
    - gdown
